receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/elasticsearch:
    endpoint: http://elasticsearch:9200/_otlp
  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, otlphttp/elasticsearch]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/prometheus]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/elasticsearch]