apiVersion: 1

datasources:
  - name: Elasticsearch
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    editable: true
    jsonData:
      esVersion: "9.5.1"
      timeField: "@timestamp"
      maxConcurrentShardRequests: 5
      logMessageField: "body.text"
      logLevelField: "severity_text"
